### ISSUE TITLE
/datafiles/oklahoma-fire-stations/download/csv/ error

### ISSUE THREAD

**Issue by jgmize** [tulsawebdevs/django-boundaryservice#1]
ERROR: Internal Server Error: /datafiles/oklahoma-fire-stations/download/csv/
Traceback (most recent call last):
  File "/home/okdata/.virtualenvs/okdata/lib/python2.6/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, _callback_args, *_callback_kwargs)
  File "/home/okdata/.virtualenvs/okdata/lib/python2.6/site-packages/django/views/generic/base.py", line 48, in view
    return self.dispatch(request, _args, *_kwargs)
  File "/home/okdata/.virtualenvs/okdata/lib/python2.6/site-packages/django/views/generic/base.py", line 69, in dispatch
    return handler(request, _args, *_kwargs)
  File "/home/okdata/oklahomadata/datafile/views.py", line 51, in get
    dw.writeheader()
AttributeError: DictWriter instance has no attribute 'writeheader'

**Comment by jgmize** [comment]
ticket accidentally opened on wrong project. closing.
